apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-python-webapp.serviceAccountName" . }}
  labels:
    {{- include "my-python-webapp.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}

