apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pod2.name }}-service
spec:
  type: {{ .Values.pod2.service.type }}
  ports:
    - port: {{ .Values.pod2.service.port }}
      targetPort: {{ .Values.pod2.service.port }}
      nodePort: {{ .Values.pod2.service.nodePort }}
  selector:
    app: {{ .Values.pod2.name }}

