apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-hook
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
      - name: post-hook
        image: busybox
        command: ['sh', '-c', 'echo "Post-install hook"']
      restartPolicy: Never

