apiVersion: v1
kind: Pod
metadata:
  name: {{ include "nodeport-multi-pod-chart.fullname" . }}-test
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: test
      image: curlimages/curl:7.78.0
      command: ['sh', '-c', 'curl -f http://{{ include "nodeport-multi-pod-chart.fullname" . }}:{{ .Values.pod1.service.port }} || exit 1']
  restartPolicy: Never

