apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # For local development, replace with appropriate storage class for production.
    path: /mnt/data
  storageClassName: manual

